In [2]:
import numpy as np

In [3]:
def QR_with_pivoting(A):
  col_norms_with_indices = np.array([(i, np.linalg.norm(A[:, i])) for i in range(0, A.shape[1])])
  sorted_col_norms_with_indices = sorted(col_norms_with_indices, key=lambda x: x[1], reverse=True)

  permutation = [int(pair[0]) for pair in sorted_col_norms_with_indices]
  P = np.eye(A.shape[1])
  P = P[permutation]

  AP = A @ P
  Q, R = np.linalg.qr(AP)

  return Q, R, P

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


Q, R, P = QR_with_pivoting(A)

print(Q @ R @ P.transpose())

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [116]:
from itertools import combinations

def brutevol(A):
  determinants = []
  n = A.shape[0]
  m = A.shape[1]

  for rows in combinations(range(n), m):
    submatrix = A[rows, :]
    det = np.linalg.det(submatrix)
    determinants.append(det)

  max_det = max(determinants, key=abs)
  return max_det

In [5]:
def max_abs_elem_ind(A):
  max_abs_value = -1
  for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        abs_value = abs(A[i, j])
        if abs_value > max_abs_value:
            max_abs_value = abs_value
            max_index = (i, j)
  return max_index

In [156]:
def maxvol(A):
  n = A.shape[0]
  r = A.shape[1]

  rev_submatrix = np.linalg.inv(A[:r, :])
  B = A @ rev_submatrix

  i, j = max_abs_elem_ind(B)
  max_rows_indices = np.arange(r)

  while i > r - 1:
    v = np.copy(B[:, j])
    v[j] -= 1
    v[i] += 1

    q = np.copy(B[i,:])
    q[j] -= 1

    B = B - np.outer(v, q)/B[i,j]
    print("Volume =", abs(np.linalg.det(A[max_rows_indices, :])))

    max_rows_indices[j] = i
    i, j = max_abs_elem_ind(B)

  return max_rows_indices

In [163]:
n = 10
r = 5

B = np.random.rand(n, n)
submatrix = B[:,:r]

indices = maxvol(submatrix)

print(brutevol(submatrix))
print(abs(np.linalg.det(submatrix[indices, :])))

Volume = 0.012697323035357762
Volume = 0.09799750415494801
Volume = 0.1523850599056173
-0.20255782515322823
0.20255782515322823
